# Generated by Django 6.0.5 on 2026-05-26 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=10, verbose_name='Unidade')),
                ('telefone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='morador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_visitante', models.CharField(max_length=100, verbose_name='Nome do visitante')),
                ('data_inicio', models.DateField(verbose_name='Data inicial')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='core.morador')),
            ],
        ),
    ]
