# Generated by Django 6.0.5 on 2026-09-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data da Visita'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='unidade',
            field=models.CharField(max_length=50, verbose_name='Unidade / Apartamento'),
        ),
    ]
